// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBECp6wwZ41oJLI4uiFCy_73sQrvMIUIhw',
    appId: '1:1007281031514:web:a69f144086fe5a85ca4b63',
    messagingSenderId: '1007281031514',
    projectId: 'codesphere-eb91c',
    authDomain: 'codesphere-eb91c.firebaseapp.com',
    storageBucket: 'codesphere-eb91c.firebasestorage.app',
    measurementId: 'G-69GNSBJ81F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrvCgBXs4-VSRGWVwGNBEbjUGPGbfs4uc',
    appId: '1:1007281031514:android:ccab9f33bc814f4aca4b63',
    messagingSenderId: '1007281031514',
    projectId: 'codesphere-eb91c',
    storageBucket: 'codesphere-eb91c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzoTWLfwMRzcj4sPJYpciapanrhXF_FD8',
    appId: '1:1007281031514:ios:d3ec49141a3bc6adca4b63',
    messagingSenderId: '1007281031514',
    projectId: 'codesphere-eb91c',
    storageBucket: 'codesphere-eb91c.firebasestorage.app',
    iosBundleId: 'com.example.codesphere',
  );
}
